# Generated by Django 5.0.7 on 2024-09-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_announcement_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
