# Generated by Django 5.0.7 on 2024-09-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_emailhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='corps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='sujet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(choices=[('Appel', 'appel'), ('Email', 'email')], max_length=10),
        ),
    ]
