# Generated by Django 5.0.7 on 2024-09-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_interaction_corps_interaction_sujet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
