# Generated by Django 5.0.7 on 2025-10-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_lead_date_cloture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='date_cloture',
        ),
    ]
