# Generated by Django 5.0.7 on 2024-09-12 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_alter_message_content_alter_message_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationparticipant',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='conversations.conversation'),
        ),
    ]
